flower_web/app/views/curve.py
# -*- coding:utf-8 -*-
import logging
import datetime
import json

from flask import Blueprint, request, render_template, redirect, jsonify, g
from flask_login import login_required
from sqlalchemy import func, desc


from app import db
from app.models.air import Air
from app.models.identification import Identification


curve = Blueprint('curve', __name__)

@curve.route("/air/", methods=["GET"])
@login_required
def air():
	device_id = request.args.to_dict().get("device_id")
	devs = []
	devices = Identification.query.all()
	for dev in devices:
		devs.append({'id': dev.id, 'description': dev.description})
	g.devices = devs

	return render_template('curve.html', device_id=device_id)
		
@curve.route("/air/", methods=["POST"])
def air_post():
	ret = {}

	ret['code'] = 200
	ret['success'] = True
	ret['result'] = {}

	data_str = request.get_data()
	logging.debug('recv POST: %s' % data_str)
	data = json.loads(data_str.decode("utf-8"))

	humidity = float(data.get('humidity'))
	fahrenheit = float(data.get('fahrenheit'))
	celsius = float(data.get('celsius'))
	identification_id = int(data.get('id'))
		
	if humidity and fahrenheit and celsius and identification_id:
		identi = Identification.query.filter_by(
			id=identification_id).first()
		if not identi:
			ret['success'] = False
			logging.info('identification_id=%d not existed.' % identification_id)
		else:
			air = Air(humidity, fahrenheit, celsius, identification_id)
			db.session.add(air)
			db.session.commit()
			logging.info('add air success.Air=%s' % air)
	return json.dumps(ret, ensure_ascii=False)


@curve.route("/air/info", methods=["GET"])
@login_required
def info():
	device_id = request.args.to_dict().get("device_id")
	ret = {}
	ret['code'] = 200
	ret['success'] = True
	ret['result'] = {}

	if not device_id:
		ret['success'] = False

	airs = db.session.query(
		func.max(Air.humidity).label('max_humidity'),
		func.min(Air.humidity).label('min_humidity'),
		func.max(Air.celsius).label('max_celsius'),
		func.min(Air.celsius).label('min_celsius'),
		func.date_format(Air.update_date, "%Y-%m-%d").label('date')).group_by(
			func.date_format(Air.update_date, "%Y-%m-%d").label('date')).filter_by(identification_id=device_id).all()
	data = dict()
	data['max_humidity'] = list()
	data['min_humidity'] = list()
	data['max_celsius'] = list()
	data['min_celsius'] = list()
	data['update_date'] = list()
	for air in airs:
		data['max_humidity'].append(air.max_humidity)
		data['min_humidity'].append(air.min_humidity)
		data['max_celsius'].append(air.max_celsius)
		data['min_celsius'].append(air.min_celsius)
		data['update_date'].append(air.date)
	ret['result'] = data

	return json.dumps(ret, ensure_ascii=False)

flower_web/app/views/login.py
# -*- coding:utf-8 -*-
import json
import logging

from flask_login import login_required, login_user, logout_user
from flask import Blueprint, request, render_template, redirect, jsonify, flash, g
from app.models.user import User
from app.models.identification import Identification

log_in = Blueprint('log_in', __name__)

@log_in.route("/login/", methods=["POST", "GET"])
def login():
	devs = []
	devices = Identification.query.all()
	for dev in devices:
		devs.append({'id': dev.id, 'description': dev.description})
	g.devices = devs
	
	if request.method == 'GET':
		return render_template('login.html')
	else:
		username = request.form.get('username')
		usepwd = request.form.get('userpwd')
		user = User.query.filter_by(name=username).first()
		if not user:
			flash('User:%s not exist' % username)
			return render_template('login.html')
		if user.pwd != usepwd:
			flash('Password is invalid')
			return render_template('login.html')

		login_user(user)
		return redirect('/relation')

		

@login_required
@log_in.route("/logout/")
def logout():
	logout_user()
	flash('You were logged out.')
	return redirect('/')








	

flower_web/app/views/regist.py
# -*- coding:utf-8 -*-
import json
import logging

from app import db
from flask_login import login_required, login_user, logout_user
from flask import Blueprint, request, render_template, redirect, jsonify, flash, g
from app.models.user import User

registuser = Blueprint('registuser', __name__)

@registuser.route("/register/", methods=["POST", "GET"])
def register():
	if request.method == 'GET':
		return render_template('register.html')
	else:
		username = request.form.get('username')
		usepwd = request.form.get('userpwd')
		usepwdagain = request.form.get('userpwdagain')
		user = User.query.filter_by(name=username).first()
		if user:
			flash('User:%s existed' % username)
			return render_template('register.html')
		if usepwd != usepwdagain:
			flash('Password and Confirm Password inconsistent!')
			return render_template('register.html')

		user = User(name=username, pwd=usepwd)            
		db.session.add(user)
		db.session.commit()
		return render_template('login.html')










	

flower_web/app/templates/base.html
<html lang="zh-CN">
<head>
	<meta name="viewport" content="width=device-width" />
	<title>{% block title %}Hello Flower{% endblock %}</title>

	{% block css %}
	<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" />
	<!-- Custom styles for this template -->
	<!-- <link href="{{ url_for('static', filename='css/starter-template.css')}}" rel="stylesheet"> -->
	{% endblock %}
	
	{% block js %}
	<script src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
	<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
	<script type="text/javascript">
		$(document).ready(function(){
			var location = window.location.href;
			// var id = location.substring(location.lastIndexOf(":")+1);
			var arr = location.split('/');
			var id = arr[3];
			$("#"+id).addClass("active");
		})
	</script>
	{% endblock %}
  </head>

  <body>
	{% block body %}
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	  <div class="container">
		<div class="navbar-header">
		  <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
			data-target="#navbar-collapse" aria-expanded="false">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		  </button>
		  <a class="navbar-brand" href="#">Flower_web</a>
		</div>
		<div id="navbar" class="collapse navbar-collapse">
		  <ul class="nav navbar-nav">
			<li id="relation"><a href="/relation">Home</a></li>
			<li id="plant"><a href="/plant">Plant</a></li>
			<li id="device"><a href="/device">Device</a></li>
			<!-- <li id="air"><a href="/air">Curve</a></li> -->
			<li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Curve
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
					{% for device in g.devices %}
					<li><a href="/air?device_id={{device.id}}">{{ device.description }}</a></li>
					{% endfor %}
                </ul>
            </li>
			{% if current_user.is_authenticated %}
			<li id="login" class="disabled"><a href="/login">Sign in</a></li>
			<li id="logout"><a href="/logout">Sign out</a></li>
			{% else %}
			<li id="login"><a href="/login">Sign in</a></li>
			<li id="logout" class="disabled"><a href="/logout">Sign out</a></li>
			{% endif %}
		  </ul>
		</div>
	  </div>
	</nav>

	<div class="container">
	  <div class="starter-template">
		<h1>Hello Flower</h1>
		<p class="lead">This project is for my flowers. I hope that the code and flowers I love can collide with each other to create a spark of passion, light up my life and warm my heart.</p>
	  </div>

	</div>
	{% endblock %}
	
 


</body></html>

flower_web/app/templates/curve.html
{% extends "base.html" %}

{% block js %}
{{ super() }}
<script src="{{ url_for('static', filename='js/echarts.js') }}"></script>
{% endblock %}

{% block title %}
{{ super()}}
{% endblock %}

{% block body %}
{{ super()}}
	<!--为ECharts准备一个具备大小（宽高）的Dom-->
	<div id="chart" style="height:500px;border:1px solid #ccc;padding:10px;"></div>
	<script type="text/javascript">
	var myChart = echarts.init(document.getElementById('chart'));
	// 显示标题，图例和空的坐标轴
	myChart.setOption({
		title: {
			text: '传感器数据显示'
		},
		tooltip: {},
		legend: {
			data:['空气最高温度', '空气最低温度', '空气最高湿度', '空气最低湿度']
		},
		xAxis: {
			data: []
		},
		yAxis: {
			data: [...Array(100).keys()]
		},
		series: [{
			name: '空气最高温度',
			type: 'line',
			data: []
		},
		{
			name: '空气最低温度',
			type: 'line',
			data: []
		},
		{
			name: '空气最高湿度',
			type: 'line',
			data: []
		},
		{
			name: '空气最低湿度',
			type: 'line',
			data: []
		}]
	});

	// 异步加载数据
	$.get('/air/info?device_id={{ device_id }}').done(function (data) {
		json_data = JSON.parse(data)

		myChart.setOption({
			toolbox: {
        		feature: {
            		saveAsImage: {}
        		}
    		},
			tooltip: {
        		trigger: 'axis'
    		},
			grid: {
        		left: '3%',
        		right: '4%',
        		bottom: '3%',
        		containLabel: true
    		},
			yAxis: {
				type: 'value',
				data: [...Array(100).keys()]
			},
			xAxis: {
				type: 'category',
				boundaryGap: false,
				data: json_data.result.update_date
			},
			legend: {
				data:['空气最高温度', '空气最低温度', '空气最高湿度', '空气最低湿度']
            },
			series: [{
				name: '空气最高温度', 
				type: 'line',
				data: json_data.result.max_celsius
			},
			{
				name: '空气最低温度',
				type: 'line',
				data: json_data.result.min_celsius
			},
			{
				name: '空气最高湿度',
				type: 'line',
				data: json_data.result.max_humidity
			},
			{
				name: '空气最低湿度',
				type: 'line',
				data: json_data.result.min_humidity//.map(parseFloat)
			}]
		});
	});
	</script>
{% endblock %}

{% block css %}
{{ super() }}
{% endblock %}





flower_web/app/templates/list.html
{% extends "base.html" %}

{% block title %}
{{super()}}
{% endblock %}

{% block css %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-table/dist/bootstrap-table.min.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/list.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css') }}" />
{% endblock %}

{% block js %}
{{super()}}
<script src="{{ url_for('static', filename='bootstrap-table/dist/bootstrap-table.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap-table/dist/locale/bootstrap-table-zh-CN.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap-table/dist/extensions/editable/bootstrap-table-editable.js') }}"></script>
<script src="{{ url_for('static', filename='x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js') }}"></script>
<style>
    .panel-body {
        width: 1170px;
        margin: auto;
    }
</style>
{% endblock %}

{% block body %}
{{super()}}
<div class="panel-body" style="padding-bottom:0px;">     
    <div id="toolbar" class="btn-group">
        <button id="btn_add" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-plus" aria-hidden="true" ></span>新增
        </button>
        <button id="getTableData" class="btn btn-default">
            <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>保存
        </button>
        <!-- <button id="btn_edit" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>修改
        </button> -->
        <button id="btn_delete" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>删除
        </button>
        <!-- <button id="btn_save" type="button" class="btn btn-default">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>保存
        </button> -->
    </div>
    <table id="table"></table>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flash">
                {% for message in messages %}
                    <div class="alert alert-warning" style="text-align: center">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <strong>{{ message }}</strong></div>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
</div>


<script type="text/javascript">
function get_cols() {
    var cols_json = JSON.parse('{{headers|tojson}}');
    var cols = [];
    cols.push({title: 'state', field: 'state', checkbox: true, align: 'center', valign: 'middle', editable: false, url: ''});
    for(var i=0; i < cols_json.length; i++) {
        cols.push({
            title: cols_json[i]['title'], 
            field: cols_json[i]['field'], 
            align: cols_json[i]['align'], 
            url:  cols_json[i]['editable']?cols_json[i]['url']:'',
            editable: cols_json[i]['editable']?{
                type: cols_json[i]['type'], 
                title: cols_json[i]['title'],
                source: sourceData(cols_json[i]['url']),
            }: false, 
            });
    }
    cols.push({title: '操作', align: 'center', valign: 'middle', formatter:"operateFormatter", editable: false})
    return cols;
};

function sourceData(url) {
    var result = [];
    $.ajax({
        url: url,
        async: false,
        type: "get",
        data: {},
        success: function (data, status) {
            var eachData = JSON.parse(data).rows;
            $.each(eachData, function (key, value) {
                result.push({ value: value.id, text: value.name || value.description});
            });
        }
    });
    return result;
}
function operateFormatter(value, row, index) {
    // return [
    // '<a href="javascript:modify(' + row.id + ')" title="modify">' +
    // '<i class="glyphicon glyphicon-pencil"></i>修改' +
    // '</a>',
    // '<a class="remove" href="javascript:remove(' + row.id + ')" title="remove">' +
    // '<i class="glyphicon glyphicon-remove"></i>删除' +
    // '</a>'
    // ].join('');
    return [
    '<a class="remove" href="javascript:remove(' + row.id + ')" title="remove">' +
    '<i class="glyphicon glyphicon-remove"></i>删除' +
    '</a>',
    ].join('');
}

function getIdSelections() {
    return $.map($('#table').bootstrapTable('getSelections'), function (row) {
        return row.id
    })
};

function modify(val) {
    alert(val)
};

function remove(rowid) {
    if(confirm("您确定删除第"+ rowid + "行吗？")) {
        $.ajax({
            method: "delete",
			url: '{{url}}',
            contentType: "application/json",
			data: JSON.stringify({'ids': [rowid]}),
            dataType: "json",
			async: true,
			success: function (res) {		
                if(res.success == false) {
                    alert(res.message);
                }
                else {
                    $("#table").bootstrapTable('refresh');
                }
			}
		}); 
    }
};

function queryParams(params) {
    var temp = {   //这里的键的名字和控制器的变量名必须一直，这边改动，控制器也需要改成一样的
        pageNum: params.pageNumber,
        pageSize: params.pageSize,
    };
    return temp;
};

$('#btn_add').click(function () {
    var count = $('#table').bootstrapTable('getData').length;
    $('#table').bootstrapTable('insertRow', {
                index: count,
                row: {
                    id: count + 1
                    // id: count + 1,
                    // name: '',
                    // description: ''
                }
    });
});
//新增
$('#getTableData').click(function () {
    // let dataList = JSON.parse(JSON.stringify($('#table').bootstrapTable('getData')));
    var dataList=$("#table").bootstrapTable('getSelections');
    //新增数组
    let data = [];
    for (var i = 0; i < dataList.length; i++) {
        // if (dataList[i].id == null) {
            //新增数组填充
            data.push(dataList[i]);
        // }
    }
    saveData(data);
});

$('#btn_delete').click(function () {
      var rowids = getIdSelections()
    //   $('#table').bootstrapTable('remove', {
    //     field: 'id',
    //     values: rowids
    //   })
    //   $('#remove').prop('disabled', true)
    if(confirm("您确定删除第"+rowids+"行吗？")) {
        $.ajax({
            method:"delete",
			url:'{{url}}',
			data: JSON.stringify({'ids': rowids}),
            dataType: "json",
            contentType: "application/json",
			async:true,
			success:function (res) {	
                if(res.success == false) {
                    alert(res.message);
                }
                else {
                    $("#table").bootstrapTable('refresh');
                }
                
			}

		}); 
    }
});

$('#table').bootstrapTable({
    method: 'get',
    url: '{{url}}',
    dataType: "json",
    editable:true,//开启编辑模式
    pagination: true, //前端处理分页
    singleSelect: false,//是否只能单选
    search: true, //显示搜索框，此搜索是客户端搜索，不会进服务端，所以，个人感觉意义不大
    toolbar: '#toolbar', //工具按钮用哪个容器
    striped: true, //是否显示行间隔色
    cache: false, //是否使用缓存，默认为true，所以一般情况下需要设置一下这个属性（*）
    paginationShowPageGo: true,
    showJumpto: true,
    pageNumber: 1, //初始化加载第10页，默认第一页
    pageSize: 10, //每页的记录行数（*）
    pageList: [10, 20, 50, 100], //可供选择的每页的行数（*）
    strictSearch: true,//设置为 true启用 全匹配搜索，false为模糊搜索
    showColumns: true, //显示内容列下拉框
    showRefresh: true, //显示刷新按钮
    minimumCountColumns: 2, //当列数小于此值时，将隐藏内容列下拉框
    clickToSelect: false, //设置true， 将在点击某行时，自动勾选rediobox 和 checkbox
    height: 'auto', //表格高度，如果没有设置height属性，表格自动根据记录条数决定表格高度#}
    uniqueId: "id", //每一行的唯一标识，一般为主键列
    showToggle: true, //是否显示详细视图和列表视图的切换按钮
    cardView: false, //是否显示详细视图
    sidePagination: "server", //分页方式：client客户端分页，server服务端分页（*）
    columns: get_cols(),
    queryParams: queryParams,//请求服务器时所传的参数 
    striped: true,
    onEditableSave: function (field, row, oldValue, $el) {
        // if(row.id){
        //     saveData(row);
        // }  
    },
    
});

function saveData(editData) {
    console.log(editData)
    $.ajax({
            method: 'post',
			url: '{{url}}',
            contentType: "application/json",
            dataType: "json",
			data: JSON.stringify(editData),
			async: true,
			success: function (res) {		
                $("#table").bootstrapTable('refresh');
			}
	});      
}






</script>
{% endblock %}

flower_web/app/templates/login.html
{% extends "base.html" %}

{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/login.css')}}" rel="stylesheet">
{% endblock %}

{% block js %}
{{ super() }}
{% endblock %}

{% block title %}
{{ super()}}
{% endblock %}

{% block body %}
<div class="container">
	<form action="{{ url_for('log_in.login') }}" method="post" class="form-signin">
	  <h2 class="form-signin-heading">Please sign in</h2>
	  <label for="inputEmail" class="sr-only">Email address</label>
	  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" name="username">
	  <label for="inputPassword" class="sr-only">Password</label>
	  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="" name="userpwd">
	  <div class="checkbox">
		<label>
		  <input type="checkbox" value="remember-me"> Remember me
		</label>
	  </div>
	  <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
</div>
{% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flash">
                {% for message in messages %}
                    <div class="alert alert-warning" style="text-align: center">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <strong>{{ message }}</strong></div>
                {% endfor %}
            </ul>
        {% endif %}
{% endwith %}

{% endblock %}

flower_web/app/templates/register.html
{% extends "base.html" %}

{% block css %}
{{ super() }}
<link href="{{ url_for('static', filename='css/login.css')}}" rel="stylesheet">
{% endblock %}

{% block js %}
{{ super() }}
{% endblock %}

{% block title %}
{{ super()}}
{% endblock %}

{% block body %}
<div class="container">
	<form action="{{ url_for('registuser.register') }}" method="post" class="form-signin">
	  <h2 class="form-signin-heading">Please register</h2>
	  <label for="inputEmail" class="sr-only">Email address</label>
	  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="" name="username">
	  <label for="inputPassword" class="sr-only">Password</label>
	  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required="" name="userpwd">
	  <label for="inputPasswordAgain" class="sr-only">PasswordAgain</label>
	  <input type="password" id="inputPasswordAgain" class="form-control" placeholder="PasswordAgain" required="" name="userpwdagain">
	  <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
	</form>
</div>
{% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class="flash">
                {% for message in messages %}
                    <div class="alert alert-warning" style="text-align: center">
                        <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                        <strong>{{ message }}</strong></div>
                {% endfor %}
            </ul>
        {% endif %}
{% endwith %}

{% endblock %}